export const ADMIN = "askar@gmail.com";
export const ACTIONS = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_COMMENTS: "GET_COMMENTS",
  GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
  GET_CART: "GET_CART",
  CHANGE_CART_LENGTH: "CHANGE_CART_LENGTH",
  GET_CAR: "GET_CAR",
  CHANGE_CAR_LENGTH: "CHANGE_CAR_LENGTH",
};
export const JSON_API_PRODUCTS = "http://localhost:8000/products";
